### ISSUE TITLE
Is there a detailed description of the server? Are there any documents missing? All startup items are prompted that they can't be found. Are server files missing?

### ISSUE THREAD

**Issue by sddzrxh** [JevLOMCN/mir4-launcher#1]
Is there a detailed description of the server? Are there any documents missing? All startup items are prompted that they can't be found. Are server files missing?

![QQ图片20240229034737](https://github.com/JevLOMCN/mir4-launcher/assets/42303818/d89f7939-697e-462f-874b-bfd2b501b751)

**Comment by JevLOMCN** [comment]
The server source isn't public yet, Once it's all ready then a server build and the source will be released.

**Comment by sddzrxh** [comment]
OKOK, look forward to your work.
